#!/usr/bin/env bash
#Write a Bash script that Creates the file /var/run/myscript.pid containing its PID#

# Function to handle SIGTERM and SIGQUIT signals
function sigterm_handler {
    echo "I hate the kill command"
    cleanup_and_exit
}

# Function to handle SIGINT signal
function sigint_handler {
    echo "Y U no love me?!"
}

# Function to cleanup and exit
function cleanup_and_exit {
    echo "Cleaning up and exiting..."
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals
trap 'sigterm_handler' SIGTERM SIGQUIT
trap 'sigint_handler' SIGINT

# Write PID to file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
echo "To infinity and beyond indefinitely"
while true; do
    sleep 1
done
