#!/usr/bin/env bash
#a Bash script that kills the process 7-highlander.#

pid=$(pgrep -f "7-highlander")

# Terminate the process by sending SIGTERM
if [ -n "$pid" ]; then
    echo "Stopping 7-highlander process..."
    kill "$pid"
else
    echo "7-highlander process not found."
fi
