#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.#

counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    echo "Best School"
    # Increment counter
    ((counter++))
done
