#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and#

# Initialize counter
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    # Increment counter
    ((counter++))
done
