#!/usr/bin/env bash
#a Bash script that displays:The content of the current directory. In a list format, Where only the part of the name after the first dash is displayed (refer to the example)#

# Using a for loop to iterate over files in the current directory
for file in *; do
    # Check if the file is not hidden
    if [[ ! $file == .* ]]; then
        # Extracting the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        # Displaying the name in list format
        echo "- $name_after_dash"
    fi
done
